### ISSUE TITLE
Problemas durante a instalação

### ISSUE THREAD

**Issue by romero1989** [marcelofmatos/phpnetmap#1]
Após rodar o comando: 
curl -sSL https://get.docker.com/ | sh 

apresentou o seguinte erro durante a execução do comando:

The following packages have unmet dependencies:
 docker-engine : Depends: init-system-helpers (>= 1.18~) but it is not installable
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not installable
                 Recommends: git but it is not going to be installed
                 Recommends: yubico-piv-tool (>= 1.1.0~) but it is not installable
E: Unable to correct problems, you have held broken packages.

Ambiente: Debian 7.7 64bits

**Comment by marcelofmatos** [comment]
Faz um teste usando o repositório backports

Cria um arquivo chamado **/etc/apt/sources.list.d/debian_backports.list** e adiciona dentro dele:

`deb http://ftp.br.debian.org/debian wheezy-backports main`

Atualize com:

```
apt-get update
apt-get install init-system-helpers
```

e depois execute o script de instalação do docker.

Referências:
- https://github.com/docker/docker/issues/15692#issuecomment-151726895
- http://backports.debian.org/
