### ISSUE TITLE
ficando Internal Server Error após o login

### ISSUE THREAD

**Issue by GaneshKandu** [marcelofmatos/phpnetmap#2]
<h3> IErro do Servidor Interno</h3>

Oi, eu tentando instalar phpnetmap mas quando eu estou faça o login com usuário e senha padrão que é "admin : test" eu estou recebendo erro interno do servidor

**Comment by marcelofmatos** [comment]
Olá. Vc está rodando-o usando o docker? Aparece algo nos logs do apache ao fazer o login?

**Comment by GaneshKandu** [comment]
Está bem ! obrigado
