### ISSUE TITLE
Cannot login, server error!

### ISSUE THREAD

**Issue by azmiplg78** [marcelofmatos/phpnetmap#3]
i'm using xamp ver.3.2.1
help me, i'm really need your apps, but i cann't login

**Comment by marcelofmatos** [comment]
First sorry for out of time

For historical, to run on xamp or another setup you must to check if was Rewrite and Auth support on apache configuration, for lines above:

https://github.com/marcelofmatos/phpnetmap/blob/e5dbeb20210eb2c08001a73f20eae151847c5556/.htaccess#L10

The password path file on this project was /app/.htpasswd and need to be adapted for your solution. 

But I suggested to test with Docker For Windows
